// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package contract

type ActionOutcome struct {
	// Actor corresponds to the JSON schema field "actor".
	Actor string `json:"actor"`

	// DurationMs corresponds to the JSON schema field "duration_ms".
	DurationMs *int `json:"duration_ms,omitempty"`

	// Error corresponds to the JSON schema field "error".
	Error *string `json:"error,omitempty"`

	// OK corresponds to the JSON schema field "ok".
	OK bool `json:"ok"`
}

type AgentEnvelope struct {
	// Actions corresponds to the JSON schema field "actions".
	Actions []AgentEnvelopeActionsElem `json:"actions,omitempty"`

	// Display-only supporting detail — longer free text than `subtitle`; URLs found
	// here render as clickable links. Not routed or filtered on.
	Description *string `json:"description,omitempty"`

	// EndAt corresponds to the JSON schema field "end_at".
	EndAt *int `json:"end_at,omitempty"`

	// ID corresponds to the JSON schema field "id".
	ID string `json:"id"`

	// Kind corresponds to the JSON schema field "kind".
	Kind string `json:"kind,omitempty"`

	// Metadata corresponds to the JSON schema field "metadata".
	Metadata Metadata `json:"metadata,omitempty"`

	// Outcome corresponds to the JSON schema field "outcome".
	Outcome *ActionOutcome `json:"outcome,omitempty"`

	// ParentID corresponds to the JSON schema field "parent_id".
	ParentID *string `json:"parent_id,omitempty"`

	// Source corresponds to the JSON schema field "source".
	Source *string `json:"source,omitempty"`

	// StartAt corresponds to the JSON schema field "start_at".
	StartAt *int `json:"start_at,omitempty"`

	// Status corresponds to the JSON schema field "status".
	Status *EnvelopeStatus `json:"status,omitempty"`

	// Display-only secondary label, one short line rendered under the title (e.g.
	// 'developer · session-3'). Never routed or filtered on.
	Subtitle *string `json:"subtitle,omitempty"`

	// Tags corresponds to the JSON schema field "tags".
	Tags []string `json:"tags,omitempty"`

	// Title corresponds to the JSON schema field "title".
	Title string `json:"title"`

	// Type corresponds to the JSON schema field "type".
	Type *string `json:"type,omitempty"`

	// URL corresponds to the JSON schema field "url".
	URL *string `json:"url,omitempty"`

	// Tenancy / routing key — the workspace profile this envelope belongs to.
	// Routable, not display: it is a column on `agent_state` and a filter in
	// `/api/agent_events/search`. None means unscoped/global.
	Workspace *string `json:"workspace,omitempty"`
}

type AgentEnvelopeActionsElem map[string]interface{}

type EnvelopeStatus string

const EnvelopeStatusActive EnvelopeStatus = "active"
const EnvelopeStatusBlocked EnvelopeStatus = "blocked"
const EnvelopeStatusDone EnvelopeStatus = "done"
const EnvelopeStatusFailed EnvelopeStatus = "failed"
const EnvelopeStatusNeedsAction EnvelopeStatus = "needs_action"
const EnvelopeStatusUpcoming EnvelopeStatus = "upcoming"

type Metadata map[string]interface{}
