[macos]
# Update ansible_host with the VM's IP (discovered via ARP on 192.168.64.0/24)
# brainbox-macos-template ansible_host=192.168.64.10 ansible_user=phantomink ansible_ssh_private_key_file=~/.ssh/id_ed25519
brainbox-macos-template ansible_host=192.168.64.3 ansible_user=phantomink ansible_ssh_private_key_file=~/workspaces/profiles/personal/.ssh/id_ed25519

[macos:vars]
ansible_python_interpreter=/usr/bin/python3
