[windows]
# Update ansible_host with the VM's IP or use localhost with port forwarding
brainbox-windows-template ansible_host=localhost ansible_port=2200 ansible_user=developer ansible_ssh_private_key_file=~/.ssh/id_ed25519

[windows:vars]
ansible_connection=ssh
ansible_shell_type=cmd
