// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {brainbox} from '../models';
import {main} from '../models';

export function AddNFSExport(arg1:string):Promise<void>;

export function AddRepo(arg1:brainbox.AddRepoRequest):Promise<brainbox.Repo>;

export function BrowseFolder():Promise<string>;

export function CancelPlaybook(arg1:string):Promise<void>;

export function CancelTask(arg1:string):Promise<void>;

export function CompleteChannel(arg1:string,arg2:brainbox.CompleteChannelRequest):Promise<brainbox.Channel>;

export function CreateAgent(arg1:brainbox.CreateAgentRequest):Promise<brainbox.AgentDefinition>;

export function CreateChannel(arg1:brainbox.CreateChannelRequest):Promise<brainbox.Channel>;

export function CreatePlaybook(arg1:brainbox.CreatePlaybookRequest):Promise<brainbox.Playbook>;

export function CreateProfile(arg1:string):Promise<main.Profile>;

export function CreateSession(arg1:brainbox.CreateSessionRequest):Promise<brainbox.SessionActionResponse>;

export function CreateWorktree(arg1:brainbox.CreateWorktreeRequest):Promise<brainbox.Worktree>;

export function CreateWorktreeSession(arg1:string):Promise<brainbox.WorktreeSessionResponse>;

export function DeleteAgent(arg1:string):Promise<void>;

export function DeleteArtifact(arg1:string):Promise<void>;

export function DeleteChannel(arg1:string):Promise<void>;

export function DeleteOllamaModel(arg1:string):Promise<void>;

export function DeletePlaybook(arg1:string):Promise<void>;

export function DeleteProfile(arg1:string,arg2:boolean):Promise<void>;

export function DeleteRepo(arg1:string):Promise<void>;

export function DeleteRunner(arg1:string):Promise<void>;

export function DeleteSession(arg1:string):Promise<brainbox.SessionActionResponse>;

export function DeleteWorktree(arg1:string):Promise<void>;

export function DownloadArtifact(arg1:string):Promise<Array<number>>;

export function ExportSecretsTemplate(arg1:string):Promise<string>;

export function FindClaudeProcesses():Promise<Array<main.LocalProcess>>;

export function FocusTerminalTab(arg1:string):Promise<void>;

export function GetAPILogs(arg1:number):Promise<Array<main.LogEntry>>;

export function GetActiveProfile():Promise<main.Profile>;

export function GetAgent(arg1:string):Promise<brainbox.AgentDefinition>;

export function GetChannel(arg1:string):Promise<brainbox.Channel>;

export function GetChannelMessages(arg1:string,arg2:string):Promise<Array<brainbox.ChannelMessage>>;

export function GetConfig():Promise<main.Config>;

export function GetContainerDiskUsage():Promise<Array<main.ContainerDiskStat>>;

export function GetContainerMetrics():Promise<Array<brainbox.ContainerMetrics>>;

export function GetDiskBreakdown():Promise<main.DiskBreakdown>;

export function GetDiskOverview():Promise<main.DiskOverview>;

export function GetDockerStats():Promise<Array<main.ContainerStat>>;

export function GetHubState():Promise<brainbox.HubState>;

export function GetLangfuseHealth():Promise<brainbox.HealthStatus>;

export function GetMessageLog():Promise<Array<brainbox.Message>>;

export function GetMetricsHistory():Promise<Array<brainbox.MetricsSample>>;

export function GetPlatform():Promise<string>;

export function GetPlaybook(arg1:string):Promise<brainbox.Playbook>;

export function GetProfileColors():Promise<Record<string, string>>;

export function GetProfileSecrets(arg1:string):Promise<Array<main.SecretKeyStatus>>;

export function GetRepoActivity(arg1:string):Promise<Array<main.RepoEvent>>;

export function GetRepoBranches(arg1:string):Promise<Array<main.RepoBranch>>;

export function GetRepoCIStatus(arg1:string,arg2:string):Promise<main.CIStatus>;

export function GetRepoPRs(arg1:string):Promise<Array<main.RepoPR>>;

export function GetSessionTraces(arg1:string,arg2:number):Promise<Array<brainbox.Trace>>;

export function GetSessions():Promise<Array<brainbox.Session>>;

export function GetSessionsMetricsHistory():Promise<Record<string, Array<brainbox.SessionMetricsSample>>>;

export function GetSystemInfo():Promise<main.SystemInfo>;

export function GetTraceDetail(arg1:string):Promise<brainbox.TraceDetail>;

export function GetWorktree(arg1:string):Promise<brainbox.Worktree>;

export function LaunchTeam(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string):Promise<brainbox.SessionActionResponse>;

export function ListAgents():Promise<Array<brainbox.AgentDefinition>>;

export function ListArtifacts(arg1:string):Promise<Array<brainbox.Artifact>>;

export function ListBackups():Promise<Array<string>>;

export function ListChannels():Promise<Array<brainbox.Channel>>;

export function ListNFSExports():Promise<Array<main.NFSExport>>;

export function ListOllamaModels():Promise<Array<brainbox.OllamaModel>>;

export function ListPlaybooks(arg1:string):Promise<Array<brainbox.Playbook>>;

export function ListProfileDirs(arg1:string):Promise<Array<string>>;

export function ListRepos():Promise<Array<brainbox.Repo>>;

export function ListRunners():Promise<Array<brainbox.Runner>>;

export function ListServices():Promise<Array<main.ServiceStatus>>;

export function ListTasks(arg1:string):Promise<Array<brainbox.Task>>;

export function ListWorktrees(arg1:string):Promise<Array<brainbox.Worktree>>;

export function PostChannelMessage(arg1:string,arg2:brainbox.PostChannelMessageRequest):Promise<brainbox.ChannelMessage>;

export function PullOllamaModel(arg1:string):Promise<string>;

export function PurgeBackup(arg1:string):Promise<void>;

export function RemoveNFSExport(arg1:string):Promise<void>;

export function RestartBrainboxAPI():Promise<void>;

export function RestoreProfile(arg1:string):Promise<void>;

export function RunPlaybook(arg1:string,arg2:string):Promise<brainbox.Playbook>;

export function RunPreflightChecks():Promise<Array<main.PreflightCheck>>;

export function ScanDiskUsage():Promise<main.DiskOverview>;

export function ScanProfiles():Promise<Array<main.Profile>>;

export function SetActiveProfile(arg1:string):Promise<void>;

export function SetConfig(arg1:string,arg2:string,arg3:string):Promise<void>;

export function SetProfileColor(arg1:string,arg2:string):Promise<void>;

export function SetServiceConfig(arg1:string,arg2:boolean,arg3:string,arg4:string,arg5:boolean):Promise<void>;

export function SetTheme(arg1:string):Promise<void>;

export function StartRunnerPairing(arg1:string,arg2:number):Promise<brainbox.PairingTicket>;

export function StartService(arg1:string):Promise<void>;

export function StartSession(arg1:string):Promise<brainbox.SessionActionResponse>;

export function StopService(arg1:string):Promise<void>;

export function StopSession(arg1:string):Promise<brainbox.SessionActionResponse>;

export function SubmitTask(arg1:brainbox.SubmitTaskRequest):Promise<brainbox.Task>;

export function UpdateAgent(arg1:string,arg2:brainbox.UpdateAgentRequest):Promise<brainbox.AgentDefinition>;

export function UpdateRepo(arg1:string,arg2:brainbox.UpdateRepoRequest):Promise<brainbox.Repo>;
