// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddRepo(arg1) {
  return window['go']['main']['App']['AddRepo'](arg1);
}

export function BrowseFolder() {
  return window['go']['main']['App']['BrowseFolder']();
}

export function CancelPlaybook(arg1) {
  return window['go']['main']['App']['CancelPlaybook'](arg1);
}

export function CancelTask(arg1) {
  return window['go']['main']['App']['CancelTask'](arg1);
}

export function CompleteChannel(arg1, arg2) {
  return window['go']['main']['App']['CompleteChannel'](arg1, arg2);
}

export function CreateAgent(arg1) {
  return window['go']['main']['App']['CreateAgent'](arg1);
}

export function CreateChannel(arg1) {
  return window['go']['main']['App']['CreateChannel'](arg1);
}

export function CreatePlaybook(arg1) {
  return window['go']['main']['App']['CreatePlaybook'](arg1);
}

export function CreateProfile(arg1) {
  return window['go']['main']['App']['CreateProfile'](arg1);
}

export function CreateSession(arg1) {
  return window['go']['main']['App']['CreateSession'](arg1);
}

export function CreateWorktree(arg1) {
  return window['go']['main']['App']['CreateWorktree'](arg1);
}

export function CreateWorktreeSession(arg1) {
  return window['go']['main']['App']['CreateWorktreeSession'](arg1);
}

export function DeleteAgent(arg1) {
  return window['go']['main']['App']['DeleteAgent'](arg1);
}

export function DeleteArtifact(arg1) {
  return window['go']['main']['App']['DeleteArtifact'](arg1);
}

export function DeleteChannel(arg1) {
  return window['go']['main']['App']['DeleteChannel'](arg1);
}

export function DeleteOllamaModel(arg1) {
  return window['go']['main']['App']['DeleteOllamaModel'](arg1);
}

export function DeletePlaybook(arg1) {
  return window['go']['main']['App']['DeletePlaybook'](arg1);
}

export function DeleteProfile(arg1, arg2) {
  return window['go']['main']['App']['DeleteProfile'](arg1, arg2);
}

export function DeleteRepo(arg1) {
  return window['go']['main']['App']['DeleteRepo'](arg1);
}

export function DeleteSession(arg1) {
  return window['go']['main']['App']['DeleteSession'](arg1);
}

export function DeleteWorktree(arg1) {
  return window['go']['main']['App']['DeleteWorktree'](arg1);
}

export function DownloadArtifact(arg1) {
  return window['go']['main']['App']['DownloadArtifact'](arg1);
}

export function ExportSecretsTemplate(arg1) {
  return window['go']['main']['App']['ExportSecretsTemplate'](arg1);
}

export function FindClaudeProcesses() {
  return window['go']['main']['App']['FindClaudeProcesses']();
}

export function FocusTerminalTab(arg1) {
  return window['go']['main']['App']['FocusTerminalTab'](arg1);
}

export function GetActiveProfile() {
  return window['go']['main']['App']['GetActiveProfile']();
}

export function GetAgent(arg1) {
  return window['go']['main']['App']['GetAgent'](arg1);
}

export function GetChannel(arg1) {
  return window['go']['main']['App']['GetChannel'](arg1);
}

export function GetChannelMessages(arg1, arg2) {
  return window['go']['main']['App']['GetChannelMessages'](arg1, arg2);
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetContainerDiskUsage() {
  return window['go']['main']['App']['GetContainerDiskUsage']();
}

export function GetContainerMetrics() {
  return window['go']['main']['App']['GetContainerMetrics']();
}

export function GetDockerStats() {
  return window['go']['main']['App']['GetDockerStats']();
}

export function GetHubState() {
  return window['go']['main']['App']['GetHubState']();
}

export function GetLangfuseHealth() {
  return window['go']['main']['App']['GetLangfuseHealth']();
}

export function GetMessageLog() {
  return window['go']['main']['App']['GetMessageLog']();
}

export function GetMetricsHistory() {
  return window['go']['main']['App']['GetMetricsHistory']();
}

export function GetPlatform() {
  return window['go']['main']['App']['GetPlatform']();
}

export function GetPlaybook(arg1) {
  return window['go']['main']['App']['GetPlaybook'](arg1);
}

export function GetProfileSecrets(arg1) {
  return window['go']['main']['App']['GetProfileSecrets'](arg1);
}

export function GetSessionTraces(arg1, arg2) {
  return window['go']['main']['App']['GetSessionTraces'](arg1, arg2);
}

export function GetSessions() {
  return window['go']['main']['App']['GetSessions']();
}

export function GetSessionsMetricsHistory() {
  return window['go']['main']['App']['GetSessionsMetricsHistory']();
}

export function GetSystemInfo() {
  return window['go']['main']['App']['GetSystemInfo']();
}

export function GetTraceDetail(arg1) {
  return window['go']['main']['App']['GetTraceDetail'](arg1);
}

export function GetWorktree(arg1) {
  return window['go']['main']['App']['GetWorktree'](arg1);
}

export function LaunchTeam(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['LaunchTeam'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function ListAgents() {
  return window['go']['main']['App']['ListAgents']();
}

export function ListArtifacts(arg1) {
  return window['go']['main']['App']['ListArtifacts'](arg1);
}

export function ListBackups() {
  return window['go']['main']['App']['ListBackups']();
}

export function ListChannels() {
  return window['go']['main']['App']['ListChannels']();
}

export function ListOllamaModels() {
  return window['go']['main']['App']['ListOllamaModels']();
}

export function ListPlaybooks(arg1) {
  return window['go']['main']['App']['ListPlaybooks'](arg1);
}

export function ListProfileDirs(arg1) {
  return window['go']['main']['App']['ListProfileDirs'](arg1);
}

export function ListRepos() {
  return window['go']['main']['App']['ListRepos']();
}

export function ListServices() {
  return window['go']['main']['App']['ListServices']();
}

export function ListTasks(arg1) {
  return window['go']['main']['App']['ListTasks'](arg1);
}

export function ListWorktrees(arg1) {
  return window['go']['main']['App']['ListWorktrees'](arg1);
}

export function PostChannelMessage(arg1, arg2) {
  return window['go']['main']['App']['PostChannelMessage'](arg1, arg2);
}

export function PullOllamaModel(arg1) {
  return window['go']['main']['App']['PullOllamaModel'](arg1);
}

export function PurgeBackup(arg1) {
  return window['go']['main']['App']['PurgeBackup'](arg1);
}

export function RestartBrainboxAPI() {
  return window['go']['main']['App']['RestartBrainboxAPI']();
}

export function RestoreProfile(arg1) {
  return window['go']['main']['App']['RestoreProfile'](arg1);
}

export function RunPlaybook(arg1) {
  return window['go']['main']['App']['RunPlaybook'](arg1);
}

export function RunPreflightChecks() {
  return window['go']['main']['App']['RunPreflightChecks']();
}

export function ScanProfiles() {
  return window['go']['main']['App']['ScanProfiles']();
}

export function SetActiveProfile(arg1) {
  return window['go']['main']['App']['SetActiveProfile'](arg1);
}

export function SetConfig(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetConfig'](arg1, arg2, arg3);
}

export function SetServiceConfig(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['SetServiceConfig'](arg1, arg2, arg3, arg4, arg5);
}

export function SetTheme(arg1) {
  return window['go']['main']['App']['SetTheme'](arg1);
}

export function StartService(arg1) {
  return window['go']['main']['App']['StartService'](arg1);
}

export function StartSession(arg1) {
  return window['go']['main']['App']['StartSession'](arg1);
}

export function StopService(arg1) {
  return window['go']['main']['App']['StopService'](arg1);
}

export function StopSession(arg1) {
  return window['go']['main']['App']['StopSession'](arg1);
}

export function SubmitTask(arg1) {
  return window['go']['main']['App']['SubmitTask'](arg1);
}

export function UpdateAgent(arg1, arg2) {
  return window['go']['main']['App']['UpdateAgent'](arg1, arg2);
}

export function UpdateRepo(arg1, arg2) {
  return window['go']['main']['App']['UpdateRepo'](arg1, arg2);
}
