// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {brainbox} from '../models';
import {main} from '../models';
import {opensearch} from '../models';

export function AddChannelParticipant(arg1:string,arg2:brainbox.ChannelParticipantRequest):Promise<brainbox.Channel>;

export function AttentionOpenTarget(arg1:string):Promise<main.OpenTarget>;

export function AttentionRespond(arg1:string,arg2:string):Promise<void>;

export function AttentionRetry(arg1:string):Promise<void>;

export function BrowseFolder():Promise<string>;

export function BrowseProfileFiles(arg1:string):Promise<Array<string>>;

export function BuildProfileImage(arg1:main.ProfileImageBuildRequest):Promise<void>;

export function CancelHubTask(arg1:string):Promise<void>;

export function CancelPlaybook(arg1:string):Promise<void>;

export function CancelTask(arg1:string):Promise<void>;

export function CompleteChannel(arg1:string,arg2:brainbox.CompleteChannelRequest):Promise<brainbox.Channel>;

export function CreateAgent(arg1:brainbox.CreateAgentRequest):Promise<brainbox.AgentDefinition>;

export function CreateChannel(arg1:brainbox.CreateChannelRequest):Promise<brainbox.Channel>;

export function CreatePlaybook(arg1:brainbox.CreatePlaybookRequest):Promise<brainbox.Playbook>;

export function CreateProfile(arg1:string):Promise<main.Profile>;

export function CreateSession(arg1:brainbox.CreateSessionRequest):Promise<brainbox.SessionActionResponse>;

export function DeleteAgent(arg1:string):Promise<void>;

export function DeleteAutomationRule(arg1:string):Promise<void>;

export function DeleteChain(arg1:string):Promise<void>;

export function DeleteChannel(arg1:string):Promise<void>;

export function DeleteCollectJob(arg1:string):Promise<void>;

export function DeleteOllamaModel(arg1:string):Promise<void>;

export function DeletePlaybook(arg1:string):Promise<void>;

export function DeleteProfile(arg1:string,arg2:boolean):Promise<void>;

export function DeleteProfileImageRecord(arg1:string):Promise<void>;

export function DeleteRunner(arg1:string):Promise<void>;

export function DeleteSchedule(arg1:string):Promise<void>;

export function DeleteSession(arg1:string):Promise<brainbox.SessionActionResponse>;

export function DisableLocalRunner():Promise<void>;

export function DismissAttention(arg1:string):Promise<void>;

export function EnableLocalRunner(arg1:string):Promise<void>;

export function EnqueueTask(arg1:main.EnqueueTaskRequest):Promise<string>;

export function ExportSecretsTemplate(arg1:string):Promise<string>;

export function FetchMetricUrl(arg1:string,arg2:string,arg3:string,arg4:string):Promise<string>;

export function FindClaudeProcesses():Promise<Array<main.LocalProcess>>;

export function FocusTerminalTab(arg1:string):Promise<void>;

export function GetAPILogs(arg1:number):Promise<Array<main.LogEntry>>;

export function GetActiveProfile():Promise<main.Profile>;

export function GetAgentRole(arg1:string):Promise<brainbox.AgentDefinition>;

export function GetAppLogs():Promise<Array<string>>;

export function GetChannel(arg1:string):Promise<brainbox.Channel>;

export function GetChannelMessages(arg1:string,arg2:string):Promise<Array<brainbox.ChannelMessage>>;

export function GetConfig():Promise<main.Config>;

export function GetContainerDiskUsage():Promise<Array<main.ContainerDiskStat>>;

export function GetContainerMetrics():Promise<Array<brainbox.ContainerMetrics>>;

export function GetDashboardLayout(arg1:string):Promise<string>;

export function GetDiskBreakdown():Promise<main.DiskBreakdown>;

export function GetDiskOverview():Promise<main.DiskOverview>;

export function GetDockerStats():Promise<Array<main.ContainerStat>>;

export function GetHubState():Promise<main.HubStateView>;

export function GetLANIP():Promise<string>;

export function GetLangfuseHealth():Promise<brainbox.HealthStatus>;

export function GetLatestCollectedEntry(arg1:string,arg2:string):Promise<main.CollectedEntry>;

export function GetLocalRunnerStatus():Promise<main.LocalRunnerStatus>;

export function GetMatchingRules(arg1:string,arg2:string):Promise<Array<main.AutomationRule>>;

export function GetMessageLog():Promise<Array<brainbox.Message>>;

export function GetMetricsHistory():Promise<Array<brainbox.MetricsSample>>;

export function GetOTLPHost():Promise<string>;

export function GetObservabilityOverview(arg1:string):Promise<opensearch.Overview>;

export function GetPlatform():Promise<string>;

export function GetPlaybook(arg1:string):Promise<brainbox.Playbook>;

export function GetProfileColors():Promise<Record<string, string>>;

export function GetProfileEnvKey(arg1:string):Promise<string>;

export function GetProfileImageInfo(arg1:string):Promise<main.ProfileImageRow|boolean>;

export function GetProfileSecrets(arg1:string):Promise<Array<main.SecretKeyStatus>>;

export function GetRegistrySettings():Promise<Record<string, string>>;

export function GetRemoteProfileImageStatus(arg1:string):Promise<any>;

export function GetSessionHistory(arg1:number,arg2:number):Promise<Array<brainbox.SessionHistoryEntry>>;

export function GetSessionTraces(arg1:string,arg2:number):Promise<Array<brainbox.Trace>>;

export function GetSessions(arg1:string):Promise<Array<brainbox.Session>>;

export function GetSessionsMetricsHistory():Promise<Record<string, Array<brainbox.SessionMetricsSample>>>;

export function GetSystemInfo():Promise<main.SystemInfo>;

export function GetTask(arg1:string):Promise<main.TaskRow>;

export function GetTaskLineage(arg1:string):Promise<Array<main.HubTask>>;

export function GetTaskStats(arg1:number):Promise<main.TaskStats>;

export function GetTraceDetail(arg1:string):Promise<brainbox.TraceDetail>;

export function GetWidgetCount(arg1:string,arg2:string):Promise<number>;

export function LaunchTeam(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string):Promise<brainbox.SessionActionResponse>;

export function ListAgentRoles():Promise<Array<brainbox.AgentDefinition>>;

export function ListAgents():Promise<Array<main.DetectedAgent>>;

export function ListAttention(arg1:string):Promise<Array<main.AttentionItem>>;

export function ListAutomationRules(arg1:string):Promise<Array<main.AutomationRule>>;

export function ListBackups():Promise<Array<string>>;

export function ListChainRuns(arg1:string,arg2:number):Promise<Array<main.ChainRunRow>>;

export function ListChains():Promise<Array<main.Chain>>;

export function ListChannels(arg1:string):Promise<Array<brainbox.Channel>>;

export function ListCollectJobs(arg1:string):Promise<Array<main.CollectJob>>;

export function ListCollectedEntries(arg1:string,arg2:string,arg3:string):Promise<Array<main.CollectedEntry>>;

export function ListHubTasks(arg1:string,arg2:string):Promise<Array<main.HubTask>>;

export function ListOllamaModels():Promise<Array<brainbox.OllamaModel>>;

export function ListPlaybooks(arg1:string):Promise<Array<brainbox.Playbook>>;

export function ListProfileDirs(arg1:string):Promise<Array<string>>;

export function ListProfileImages():Promise<Array<main.ProfileImageRow>>;

export function ListRunners():Promise<Array<brainbox.Runner>>;

export function ListSchedules(arg1:string):Promise<Array<main.ScheduleRow>>;

export function ListServices():Promise<Array<main.ServiceStatus>>;

export function ListTasks(arg1:string,arg2:string,arg3:number):Promise<Array<main.TaskRow>>;

export function ListUpcomingFires(arg1:number):Promise<Array<main.UpcomingFire>>;

export function OpenLocalSession(arg1:string):Promise<void>;

export function PostChannelMessage(arg1:string,arg2:brainbox.PostChannelMessageRequest):Promise<brainbox.ChannelMessage>;

export function PreviewDispatch(arg1:brainbox.DispatchPreviewRequest):Promise<brainbox.DispatchPreview>;

export function PullOllamaModel(arg1:string):Promise<string>;

export function PurgeBackup(arg1:string):Promise<void>;

export function RemoveChannelParticipant(arg1:string,arg2:string):Promise<brainbox.Channel>;

export function RescanAgents():Promise<Array<main.DetectedAgent>>;

export function RestartBrainboxAPI():Promise<void>;

export function RestoreAttention(arg1:string):Promise<void>;

export function RestoreProfile(arg1:string):Promise<void>;

export function RetryTask(arg1:string):Promise<void>;

export function RunChain(arg1:string,arg2:string,arg3:string):Promise<string>;

export function RunCollectJobNow(arg1:string):Promise<void>;

export function RunMetricScript(arg1:string,arg2:string):Promise<string>;

export function RunPlaybook(arg1:string,arg2:string,arg3:string):Promise<brainbox.Playbook>;

export function RunPreflightChecks():Promise<Array<main.PreflightCheck>>;

export function SaveAutomationRule(arg1:main.AutomationRule):Promise<void>;

export function SaveChain(arg1:main.Chain):Promise<main.Chain>;

export function SaveCollectJob(arg1:main.CollectJob):Promise<main.CollectJob>;

export function SaveDashboardLayout(arg1:string,arg2:string):Promise<void>;

export function SaveSchedule(arg1:main.ScheduleRow):Promise<main.ScheduleRow>;

export function ScanDiskUsage():Promise<main.DiskOverview>;

export function ScanProfiles():Promise<Array<main.Profile>>;

export function SetActiveProfile(arg1:string):Promise<void>;

export function SetAgentEnabled(arg1:string,arg2:boolean):Promise<void>;

export function SetConfig(arg1:string,arg2:string,arg3:string):Promise<void>;

export function SetOTLPHost(arg1:string):Promise<void>;

export function SetProfileColor(arg1:string,arg2:string):Promise<void>;

export function SetRegistrySettings(arg1:string,arg2:string):Promise<void>;

export function SetServiceConfig(arg1:string,arg2:boolean,arg3:string,arg4:string,arg5:boolean):Promise<void>;

export function SetTheme(arg1:string):Promise<void>;

export function StartRunnerPairing(arg1:string,arg2:number,arg3:string):Promise<brainbox.PairingTicket>;

export function StartService(arg1:string):Promise<void>;

export function StartSession(arg1:string):Promise<brainbox.SessionActionResponse>;

export function StopService(arg1:string):Promise<void>;

export function StopSession(arg1:string):Promise<brainbox.SessionActionResponse>;

export function SubmitTask(arg1:brainbox.SubmitTaskRequest):Promise<main.HubTask>;

export function SubmitTaskAndWait(arg1:brainbox.WaitForTaskRequest):Promise<brainbox.WaitForTaskResponse>;

export function TailLogs(arg1:string,arg2:number):Promise<Array<opensearch.LogEntry>>;

export function TriggerRule(arg1:string,arg2:string,arg3:string):Promise<void>;

export function UpdateAgent(arg1:string,arg2:brainbox.UpdateAgentRequest):Promise<brainbox.AgentDefinition>;

export function UpdatePlaybook(arg1:string,arg2:brainbox.UpdatePlaybookRequest):Promise<brainbox.Playbook>;

export function UsableAgents():Promise<Array<main.DetectedAgent>>;
