// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddChannelParticipant(arg1, arg2) {
  return window['go']['main']['App']['AddChannelParticipant'](arg1, arg2);
}

export function BrowseFolder() {
  return window['go']['main']['App']['BrowseFolder']();
}

export function BrowseProfileFiles(arg1) {
  return window['go']['main']['App']['BrowseProfileFiles'](arg1);
}

export function BuildProfileImage(arg1) {
  return window['go']['main']['App']['BuildProfileImage'](arg1);
}

export function CancelHubTask(arg1) {
  return window['go']['main']['App']['CancelHubTask'](arg1);
}

export function CancelPlaybook(arg1) {
  return window['go']['main']['App']['CancelPlaybook'](arg1);
}

export function CancelTask(arg1) {
  return window['go']['main']['App']['CancelTask'](arg1);
}

export function CompleteChannel(arg1, arg2) {
  return window['go']['main']['App']['CompleteChannel'](arg1, arg2);
}

export function CreateAgent(arg1) {
  return window['go']['main']['App']['CreateAgent'](arg1);
}

export function CreateChannel(arg1) {
  return window['go']['main']['App']['CreateChannel'](arg1);
}

export function CreatePlaybook(arg1) {
  return window['go']['main']['App']['CreatePlaybook'](arg1);
}

export function CreateProfile(arg1) {
  return window['go']['main']['App']['CreateProfile'](arg1);
}

export function CreateSession(arg1) {
  return window['go']['main']['App']['CreateSession'](arg1);
}

export function DeleteAgent(arg1) {
  return window['go']['main']['App']['DeleteAgent'](arg1);
}

export function DeleteAutomationRule(arg1) {
  return window['go']['main']['App']['DeleteAutomationRule'](arg1);
}

export function DeleteChain(arg1) {
  return window['go']['main']['App']['DeleteChain'](arg1);
}

export function DeleteChannel(arg1) {
  return window['go']['main']['App']['DeleteChannel'](arg1);
}

export function DeleteCollectJob(arg1) {
  return window['go']['main']['App']['DeleteCollectJob'](arg1);
}

export function DeleteOllamaModel(arg1) {
  return window['go']['main']['App']['DeleteOllamaModel'](arg1);
}

export function DeletePlaybook(arg1) {
  return window['go']['main']['App']['DeletePlaybook'](arg1);
}

export function DeleteProfile(arg1, arg2) {
  return window['go']['main']['App']['DeleteProfile'](arg1, arg2);
}

export function DeleteProfileImageRecord(arg1) {
  return window['go']['main']['App']['DeleteProfileImageRecord'](arg1);
}

export function DeleteRunner(arg1) {
  return window['go']['main']['App']['DeleteRunner'](arg1);
}

export function DeleteSchedule(arg1) {
  return window['go']['main']['App']['DeleteSchedule'](arg1);
}

export function DeleteSession(arg1) {
  return window['go']['main']['App']['DeleteSession'](arg1);
}

export function DisableLocalRunner() {
  return window['go']['main']['App']['DisableLocalRunner']();
}

export function DismissAttention(arg1) {
  return window['go']['main']['App']['DismissAttention'](arg1);
}

export function EnableLocalRunner(arg1) {
  return window['go']['main']['App']['EnableLocalRunner'](arg1);
}

export function EnqueueTask(arg1) {
  return window['go']['main']['App']['EnqueueTask'](arg1);
}

export function ExportSecretsTemplate(arg1) {
  return window['go']['main']['App']['ExportSecretsTemplate'](arg1);
}

export function FetchMetricUrl(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['FetchMetricUrl'](arg1, arg2, arg3, arg4);
}

export function FindClaudeProcesses() {
  return window['go']['main']['App']['FindClaudeProcesses']();
}

export function FocusTerminalTab(arg1) {
  return window['go']['main']['App']['FocusTerminalTab'](arg1);
}

export function GetAPILogs(arg1) {
  return window['go']['main']['App']['GetAPILogs'](arg1);
}

export function GetActiveProfile() {
  return window['go']['main']['App']['GetActiveProfile']();
}

export function GetAgentRole(arg1) {
  return window['go']['main']['App']['GetAgentRole'](arg1);
}

export function GetAppLogs() {
  return window['go']['main']['App']['GetAppLogs']();
}

export function GetChannel(arg1) {
  return window['go']['main']['App']['GetChannel'](arg1);
}

export function GetChannelMessages(arg1, arg2) {
  return window['go']['main']['App']['GetChannelMessages'](arg1, arg2);
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetContainerDiskUsage() {
  return window['go']['main']['App']['GetContainerDiskUsage']();
}

export function GetContainerMetrics() {
  return window['go']['main']['App']['GetContainerMetrics']();
}

export function GetDashboardLayout(arg1) {
  return window['go']['main']['App']['GetDashboardLayout'](arg1);
}

export function GetDiskBreakdown() {
  return window['go']['main']['App']['GetDiskBreakdown']();
}

export function GetDiskOverview() {
  return window['go']['main']['App']['GetDiskOverview']();
}

export function GetDockerStats() {
  return window['go']['main']['App']['GetDockerStats']();
}

export function GetHubState() {
  return window['go']['main']['App']['GetHubState']();
}

export function GetLANIP() {
  return window['go']['main']['App']['GetLANIP']();
}

export function GetLangfuseHealth() {
  return window['go']['main']['App']['GetLangfuseHealth']();
}

export function GetLatestCollectedEntry(arg1, arg2) {
  return window['go']['main']['App']['GetLatestCollectedEntry'](arg1, arg2);
}

export function GetLocalRunnerStatus() {
  return window['go']['main']['App']['GetLocalRunnerStatus']();
}

export function GetMatchingRules(arg1, arg2) {
  return window['go']['main']['App']['GetMatchingRules'](arg1, arg2);
}

export function GetMessageLog() {
  return window['go']['main']['App']['GetMessageLog']();
}

export function GetMetricsHistory() {
  return window['go']['main']['App']['GetMetricsHistory']();
}

export function GetOTLPHost() {
  return window['go']['main']['App']['GetOTLPHost']();
}

export function GetObservabilityOverview(arg1) {
  return window['go']['main']['App']['GetObservabilityOverview'](arg1);
}

export function GetPlatform() {
  return window['go']['main']['App']['GetPlatform']();
}

export function GetPlaybook(arg1) {
  return window['go']['main']['App']['GetPlaybook'](arg1);
}

export function GetProfileColors() {
  return window['go']['main']['App']['GetProfileColors']();
}

export function GetProfileEnvKey(arg1) {
  return window['go']['main']['App']['GetProfileEnvKey'](arg1);
}

export function GetProfileImageInfo(arg1) {
  return window['go']['main']['App']['GetProfileImageInfo'](arg1);
}

export function GetProfileSecrets(arg1) {
  return window['go']['main']['App']['GetProfileSecrets'](arg1);
}

export function GetRegistrySettings() {
  return window['go']['main']['App']['GetRegistrySettings']();
}

export function GetRemoteProfileImageStatus(arg1) {
  return window['go']['main']['App']['GetRemoteProfileImageStatus'](arg1);
}

export function GetSessionHistory(arg1, arg2) {
  return window['go']['main']['App']['GetSessionHistory'](arg1, arg2);
}

export function GetSessionTraces(arg1, arg2) {
  return window['go']['main']['App']['GetSessionTraces'](arg1, arg2);
}

export function GetSessions(arg1) {
  return window['go']['main']['App']['GetSessions'](arg1);
}

export function GetSessionsMetricsHistory() {
  return window['go']['main']['App']['GetSessionsMetricsHistory']();
}

export function GetSystemInfo() {
  return window['go']['main']['App']['GetSystemInfo']();
}

export function GetTask(arg1) {
  return window['go']['main']['App']['GetTask'](arg1);
}

export function GetTaskLineage(arg1) {
  return window['go']['main']['App']['GetTaskLineage'](arg1);
}

export function GetTaskStats(arg1) {
  return window['go']['main']['App']['GetTaskStats'](arg1);
}

export function GetTraceDetail(arg1) {
  return window['go']['main']['App']['GetTraceDetail'](arg1);
}

export function GetWidgetCount(arg1, arg2) {
  return window['go']['main']['App']['GetWidgetCount'](arg1, arg2);
}

export function LaunchTeam(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['LaunchTeam'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function ListAgentRoles() {
  return window['go']['main']['App']['ListAgentRoles']();
}

export function ListAgents() {
  return window['go']['main']['App']['ListAgents']();
}

export function ListAttention(arg1) {
  return window['go']['main']['App']['ListAttention'](arg1);
}

export function ListAutomationRules(arg1) {
  return window['go']['main']['App']['ListAutomationRules'](arg1);
}

export function ListBackups() {
  return window['go']['main']['App']['ListBackups']();
}

export function ListChainRuns(arg1, arg2) {
  return window['go']['main']['App']['ListChainRuns'](arg1, arg2);
}

export function ListChains() {
  return window['go']['main']['App']['ListChains']();
}

export function ListChannels(arg1) {
  return window['go']['main']['App']['ListChannels'](arg1);
}

export function ListCollectJobs(arg1) {
  return window['go']['main']['App']['ListCollectJobs'](arg1);
}

export function ListCollectedEntries(arg1, arg2, arg3) {
  return window['go']['main']['App']['ListCollectedEntries'](arg1, arg2, arg3);
}

export function ListHubTasks(arg1, arg2) {
  return window['go']['main']['App']['ListHubTasks'](arg1, arg2);
}

export function ListOllamaModels() {
  return window['go']['main']['App']['ListOllamaModels']();
}

export function ListPlaybooks(arg1) {
  return window['go']['main']['App']['ListPlaybooks'](arg1);
}

export function ListProfileDirs(arg1) {
  return window['go']['main']['App']['ListProfileDirs'](arg1);
}

export function ListProfileImages() {
  return window['go']['main']['App']['ListProfileImages']();
}

export function ListRunners() {
  return window['go']['main']['App']['ListRunners']();
}

export function ListSchedules(arg1) {
  return window['go']['main']['App']['ListSchedules'](arg1);
}

export function ListServices() {
  return window['go']['main']['App']['ListServices']();
}

export function ListTasks(arg1, arg2, arg3) {
  return window['go']['main']['App']['ListTasks'](arg1, arg2, arg3);
}

export function ListUpcomingFires(arg1) {
  return window['go']['main']['App']['ListUpcomingFires'](arg1);
}

export function OpenLocalSession(arg1) {
  return window['go']['main']['App']['OpenLocalSession'](arg1);
}

export function PostChannelMessage(arg1, arg2) {
  return window['go']['main']['App']['PostChannelMessage'](arg1, arg2);
}

export function PreviewDispatch(arg1) {
  return window['go']['main']['App']['PreviewDispatch'](arg1);
}

export function PullOllamaModel(arg1) {
  return window['go']['main']['App']['PullOllamaModel'](arg1);
}

export function PurgeBackup(arg1) {
  return window['go']['main']['App']['PurgeBackup'](arg1);
}

export function RemoveChannelParticipant(arg1, arg2) {
  return window['go']['main']['App']['RemoveChannelParticipant'](arg1, arg2);
}

export function RescanAgents() {
  return window['go']['main']['App']['RescanAgents']();
}

export function RestartBrainboxAPI() {
  return window['go']['main']['App']['RestartBrainboxAPI']();
}

export function RestoreAttention(arg1) {
  return window['go']['main']['App']['RestoreAttention'](arg1);
}

export function RestoreProfile(arg1) {
  return window['go']['main']['App']['RestoreProfile'](arg1);
}

export function RetryTask(arg1) {
  return window['go']['main']['App']['RetryTask'](arg1);
}

export function RunChain(arg1, arg2, arg3) {
  return window['go']['main']['App']['RunChain'](arg1, arg2, arg3);
}

export function RunCollectJobNow(arg1) {
  return window['go']['main']['App']['RunCollectJobNow'](arg1);
}

export function RunMetricScript(arg1, arg2) {
  return window['go']['main']['App']['RunMetricScript'](arg1, arg2);
}

export function RunPlaybook(arg1, arg2, arg3) {
  return window['go']['main']['App']['RunPlaybook'](arg1, arg2, arg3);
}

export function RunPreflightChecks() {
  return window['go']['main']['App']['RunPreflightChecks']();
}

export function SaveAutomationRule(arg1) {
  return window['go']['main']['App']['SaveAutomationRule'](arg1);
}

export function SaveChain(arg1) {
  return window['go']['main']['App']['SaveChain'](arg1);
}

export function SaveCollectJob(arg1) {
  return window['go']['main']['App']['SaveCollectJob'](arg1);
}

export function SaveDashboardLayout(arg1, arg2) {
  return window['go']['main']['App']['SaveDashboardLayout'](arg1, arg2);
}

export function SaveSchedule(arg1) {
  return window['go']['main']['App']['SaveSchedule'](arg1);
}

export function ScanDiskUsage() {
  return window['go']['main']['App']['ScanDiskUsage']();
}

export function ScanProfiles() {
  return window['go']['main']['App']['ScanProfiles']();
}

export function SetActiveProfile(arg1) {
  return window['go']['main']['App']['SetActiveProfile'](arg1);
}

export function SetAgentEnabled(arg1, arg2) {
  return window['go']['main']['App']['SetAgentEnabled'](arg1, arg2);
}

export function SetConfig(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetConfig'](arg1, arg2, arg3);
}

export function SetOTLPHost(arg1) {
  return window['go']['main']['App']['SetOTLPHost'](arg1);
}

export function SetProfileColor(arg1, arg2) {
  return window['go']['main']['App']['SetProfileColor'](arg1, arg2);
}

export function SetRegistrySettings(arg1, arg2) {
  return window['go']['main']['App']['SetRegistrySettings'](arg1, arg2);
}

export function SetServiceConfig(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['SetServiceConfig'](arg1, arg2, arg3, arg4, arg5);
}

export function SetTheme(arg1) {
  return window['go']['main']['App']['SetTheme'](arg1);
}

export function StartRunnerPairing(arg1, arg2, arg3) {
  return window['go']['main']['App']['StartRunnerPairing'](arg1, arg2, arg3);
}

export function StartService(arg1) {
  return window['go']['main']['App']['StartService'](arg1);
}

export function StartSession(arg1) {
  return window['go']['main']['App']['StartSession'](arg1);
}

export function StopService(arg1) {
  return window['go']['main']['App']['StopService'](arg1);
}

export function StopSession(arg1) {
  return window['go']['main']['App']['StopSession'](arg1);
}

export function SubmitTask(arg1) {
  return window['go']['main']['App']['SubmitTask'](arg1);
}

export function TailLogs(arg1, arg2) {
  return window['go']['main']['App']['TailLogs'](arg1, arg2);
}

export function TriggerRule(arg1, arg2, arg3) {
  return window['go']['main']['App']['TriggerRule'](arg1, arg2, arg3);
}

export function UpdateAgent(arg1, arg2) {
  return window['go']['main']['App']['UpdateAgent'](arg1, arg2);
}

export function UpdatePlaybook(arg1, arg2) {
  return window['go']['main']['App']['UpdatePlaybook'](arg1, arg2);
}

export function UsableAgents() {
  return window['go']['main']['App']['UsableAgents']();
}
