// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddRepo(arg1) {
  return window['go']['main']['App']['AddRepo'](arg1);
}

export function CancelPipelineRun(arg1) {
  return window['go']['main']['App']['CancelPipelineRun'](arg1);
}

export function CancelTask(arg1) {
  return window['go']['main']['App']['CancelTask'](arg1);
}

export function CreateProfile(arg1) {
  return window['go']['main']['App']['CreateProfile'](arg1);
}

export function CreateSession(arg1) {
  return window['go']['main']['App']['CreateSession'](arg1);
}

export function DeleteArtifact(arg1) {
  return window['go']['main']['App']['DeleteArtifact'](arg1);
}

export function DeleteProfile(arg1, arg2) {
  return window['go']['main']['App']['DeleteProfile'](arg1, arg2);
}

export function DeleteRepo(arg1) {
  return window['go']['main']['App']['DeleteRepo'](arg1);
}

export function DeleteSession(arg1) {
  return window['go']['main']['App']['DeleteSession'](arg1);
}

export function DownloadArtifact(arg1) {
  return window['go']['main']['App']['DownloadArtifact'](arg1);
}

export function ExportSecretsTemplate(arg1) {
  return window['go']['main']['App']['ExportSecretsTemplate'](arg1);
}

export function FindClaudeProcesses() {
  return window['go']['main']['App']['FindClaudeProcesses']();
}

export function FocusTerminalTab(arg1) {
  return window['go']['main']['App']['FocusTerminalTab'](arg1);
}

export function GetActiveProfile() {
  return window['go']['main']['App']['GetActiveProfile']();
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetContainerMetrics() {
  return window['go']['main']['App']['GetContainerMetrics']();
}

export function GetDockerStats() {
  return window['go']['main']['App']['GetDockerStats']();
}

export function GetHubState() {
  return window['go']['main']['App']['GetHubState']();
}

export function GetLangfuseHealth() {
  return window['go']['main']['App']['GetLangfuseHealth']();
}

export function GetMessageLog() {
  return window['go']['main']['App']['GetMessageLog']();
}

export function GetPlatform() {
  return window['go']['main']['App']['GetPlatform']();
}

export function GetProfileSecrets(arg1) {
  return window['go']['main']['App']['GetProfileSecrets'](arg1);
}

export function GetSessionTraces(arg1, arg2) {
  return window['go']['main']['App']['GetSessionTraces'](arg1, arg2);
}

export function GetSessions() {
  return window['go']['main']['App']['GetSessions']();
}

export function GetSystemInfo() {
  return window['go']['main']['App']['GetSystemInfo']();
}

export function GetTraceDetail(arg1) {
  return window['go']['main']['App']['GetTraceDetail'](arg1);
}

export function ListAgents() {
  return window['go']['main']['App']['ListAgents']();
}

export function ListArtifacts(arg1) {
  return window['go']['main']['App']['ListArtifacts'](arg1);
}

export function ListBackups() {
  return window['go']['main']['App']['ListBackups']();
}

export function ListPipelineRuns() {
  return window['go']['main']['App']['ListPipelineRuns']();
}

export function ListPipelines() {
  return window['go']['main']['App']['ListPipelines']();
}

export function ListProfileDirs(arg1) {
  return window['go']['main']['App']['ListProfileDirs'](arg1);
}

export function ListRepos() {
  return window['go']['main']['App']['ListRepos']();
}

export function ListServices() {
  return window['go']['main']['App']['ListServices']();
}

export function ListTasks(arg1) {
  return window['go']['main']['App']['ListTasks'](arg1);
}

export function PurgeBackup(arg1) {
  return window['go']['main']['App']['PurgeBackup'](arg1);
}

export function RestoreProfile(arg1) {
  return window['go']['main']['App']['RestoreProfile'](arg1);
}

export function RunPreflightChecks() {
  return window['go']['main']['App']['RunPreflightChecks']();
}

export function ScanProfiles() {
  return window['go']['main']['App']['ScanProfiles']();
}

export function SetActiveProfile(arg1) {
  return window['go']['main']['App']['SetActiveProfile'](arg1);
}

export function SetConfig(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetConfig'](arg1, arg2, arg3);
}

export function SetServiceConfig(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['SetServiceConfig'](arg1, arg2, arg3, arg4, arg5);
}

export function SetTheme(arg1) {
  return window['go']['main']['App']['SetTheme'](arg1);
}

export function StartPipelineRun(arg1, arg2) {
  return window['go']['main']['App']['StartPipelineRun'](arg1, arg2);
}

export function StartService(arg1) {
  return window['go']['main']['App']['StartService'](arg1);
}

export function StartSession(arg1) {
  return window['go']['main']['App']['StartSession'](arg1);
}

export function StopService(arg1) {
  return window['go']['main']['App']['StopService'](arg1);
}

export function StopSession(arg1) {
  return window['go']['main']['App']['StopSession'](arg1);
}

export function SubmitTask(arg1) {
  return window['go']['main']['App']['SubmitTask'](arg1);
}

export function UpdateRepo(arg1, arg2) {
  return window['go']['main']['App']['UpdateRepo'](arg1, arg2);
}
