// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {brainbox} from '../models';
import {main} from '../models';
import {opensearch} from '../models';

export function AddChannelParticipant(arg1:string,arg2:brainbox.ChannelParticipantRequest):Promise<brainbox.Channel>;

export function AssistLoopTemplate(arg1:brainbox.LoopAssistRequest):Promise<brainbox.LoopAssistResult>;

export function AttentionOpenTarget(arg1:string):Promise<main.OpenTarget>;

export function AttentionRespond(arg1:string,arg2:string):Promise<void>;

export function AttentionRetry(arg1:string):Promise<void>;

export function BrowseFolder():Promise<string>;

export function BrowseProfileFiles(arg1:string):Promise<Array<string>>;

export function BuildProfileImage(arg1:main.ProfileImageBuildRequest):Promise<void>;

export function CancelHubTask(arg1:string):Promise<void>;

export function CancelLiveLoop(arg1:string,arg2:string):Promise<brainbox.LiveLoop>;

export function CancelPlaybook(arg1:string):Promise<void>;

export function CancelTask(arg1:string):Promise<void>;

export function ClearProfileServerOverride(arg1:string,arg2:string):Promise<void>;

export function CompleteChannel(arg1:string,arg2:brainbox.CompleteChannelRequest):Promise<brainbox.Channel>;

export function CreateAgent(arg1:brainbox.CreateAgentRequest):Promise<brainbox.AgentDefinition>;

export function CreateChannel(arg1:brainbox.CreateChannelRequest):Promise<brainbox.Channel>;

export function CreatePlaybook(arg1:brainbox.CreatePlaybookRequest):Promise<brainbox.Playbook>;

export function CreateProfile(arg1:string):Promise<main.Profile>;

export function CreateSession(arg1:brainbox.CreateSessionRequest):Promise<brainbox.SessionActionResponse>;

export function DeleteAgent(arg1:string):Promise<void>;

export function DeleteArtifactObject(arg1:string,arg2:string):Promise<void>;

export function DeleteAutomationRule(arg1:string):Promise<void>;

export function DeleteBundleSource(arg1:string,arg2:string):Promise<void>;

export function DeleteChannel(arg1:string):Promise<void>;

export function DeleteCollectJob(arg1:string):Promise<void>;

export function DeleteCollectJobsByOwner(arg1:string,arg2:string):Promise<number>;

export function DeleteGatewayEnv(arg1:string):Promise<void>;

export function DeleteLoopTemplate(arg1:string):Promise<void>;

export function DeleteOllamaModel(arg1:string):Promise<void>;

export function DeletePlaybook(arg1:string):Promise<void>;

export function DeleteProfile(arg1:string,arg2:boolean):Promise<void>;

export function DeleteProfileBundle(arg1:string):Promise<void>;

export function DeleteProfileImageRecord(arg1:string):Promise<void>;

export function DeleteRule(arg1:string):Promise<void>;

export function DeleteRunner(arg1:string):Promise<void>;

export function DeleteSchedule(arg1:string):Promise<void>;

export function DeleteSequence(arg1:string):Promise<void>;

export function DeleteSession(arg1:string):Promise<brainbox.SessionActionResponse>;

export function DeleteTrustRule(arg1:string,arg2:string):Promise<void>;

export function DisableLocalRunner():Promise<void>;

export function DismissAttention(arg1:string):Promise<void>;

export function DownloadArtifactObject(arg1:string,arg2:string,arg3:string):Promise<string>;

export function DryRunLoopTemplate(arg1:string,arg2:Record<string, any>):Promise<Record<string, any>>;

export function EnableLocalRunner(arg1:string):Promise<void>;

export function EnqueueTask(arg1:main.EnqueueTaskRequest):Promise<string>;

export function ExportSecretsTemplate(arg1:string):Promise<string>;

export function FetchMetricUrl(arg1:string,arg2:string,arg3:string,arg4:string):Promise<string>;

export function FindClaudeProcesses():Promise<Array<main.LocalProcess>>;

export function FocusTerminalTab(arg1:string):Promise<void>;

export function GatewayInfo():Promise<brainbox.GatewayProfilesInfo>;

export function GetAPILogs(arg1:number):Promise<Array<main.LogEntry>>;

export function GetActiveProfile():Promise<main.Profile>;

export function GetAgentRole(arg1:string):Promise<brainbox.AgentDefinition>;

export function GetAgentState(arg1:string):Promise<brainbox.AgentStateItem>;

export function GetAppLogs():Promise<Array<string>>;

export function GetArtifactPreview(arg1:string,arg2:string):Promise<main.ArtifactPreview>;

export function GetArtifactsHealth():Promise<brainbox.ArtifactsHealth>;

export function GetChannel(arg1:string):Promise<brainbox.Channel>;

export function GetChannelMessages(arg1:string,arg2:string):Promise<Array<brainbox.ChannelMessage>>;

export function GetConfig():Promise<main.Config>;

export function GetContainerDiskUsage():Promise<Array<main.ContainerDiskStat>>;

export function GetContainerMetrics():Promise<Array<brainbox.ContainerMetrics>>;

export function GetDashboardLayout(arg1:string):Promise<string>;

export function GetDiskBreakdown():Promise<main.DiskBreakdown>;

export function GetDiskOverview():Promise<main.DiskOverview>;

export function GetDockerStats():Promise<Array<main.ContainerStat>>;

export function GetGatewayEnv(arg1:string):Promise<Record<string, string>>;

export function GetHiddenProfiles():Promise<Array<string>>;

export function GetHubState():Promise<main.HubStateView>;

export function GetLANIP():Promise<string>;

export function GetLangfuseHealth():Promise<brainbox.HealthStatus>;

export function GetLatestCollectedEntry(arg1:string,arg2:string):Promise<main.CollectedEntry>;

export function GetLiveLoop(arg1:string):Promise<brainbox.LiveLoop>;

export function GetLiveLoopIterations(arg1:string):Promise<Array<brainbox.LiveLoopIteration>>;

export function GetLocalRunnerStatus():Promise<main.LocalRunnerStatus>;

export function GetLoopTemplate(arg1:string):Promise<brainbox.LoopTemplate>;

export function GetLoopTemplateSchema():Promise<Record<string, any>>;

export function GetMatchingRules(arg1:string,arg2:string):Promise<Array<main.AutomationRule>>;

export function GetMessageLog():Promise<Array<brainbox.Message>>;

export function GetMetricsHistory():Promise<Array<brainbox.MetricsSample>>;

export function GetMinioBrowserAddress():Promise<string>;

export function GetOTLPHost():Promise<string>;

export function GetObservabilityOverview(arg1:string):Promise<opensearch.Overview>;

export function GetOrchestrationZones(arg1:string):Promise<brainbox.OrchestrationZones>;

export function GetPlatform():Promise<string>;

export function GetPlaybook(arg1:string):Promise<brainbox.Playbook>;

export function GetProfileBundleMeta(arg1:string):Promise<brainbox.BundleMeta>;

export function GetProfileColors():Promise<Record<string, string>>;

export function GetProfileEnvKey(arg1:string):Promise<string>;

export function GetProfileImageInfo(arg1:string):Promise<main.ProfileImageRow|boolean>;

export function GetProfileSecrets(arg1:string):Promise<Array<main.SecretKeyStatus>>;

export function GetProfileServers(arg1:string):Promise<Array<brainbox.ProfileServerState>>;

export function GetRegistrySettings():Promise<Record<string, string>>;

export function GetRemoteProfileImageStatus(arg1:string):Promise<any>;

export function GetRule(arg1:string):Promise<brainbox.Rule>;

export function GetRulesStatus():Promise<brainbox.RulesStatus>;

export function GetSessionHistory(arg1:number,arg2:number):Promise<Array<brainbox.SessionHistoryEntry>>;

export function GetSessionTraces(arg1:string,arg2:number):Promise<Array<brainbox.Trace>>;

export function GetSessions(arg1:string):Promise<Array<brainbox.Session>>;

export function GetSessionsMetricsHistory():Promise<Record<string, Array<brainbox.SessionMetricsSample>>>;

export function GetSystemInfo():Promise<main.SystemInfo>;

export function GetTask(arg1:string):Promise<main.TaskRow>;

export function GetTaskLineage(arg1:string):Promise<Array<main.HubTask>>;

export function GetTaskStats(arg1:number):Promise<main.TaskStats>;

export function GetTraceDetail(arg1:string):Promise<brainbox.TraceDetail>;

export function GetTrust(arg1:string):Promise<brainbox.TrustConfig>;

export function GetWidgetCount(arg1:string,arg2:string):Promise<number>;

export function HeadArtifactObject(arg1:string,arg2:string):Promise<brainbox.ArtifactObjectHead>;

export function ImportEnvFile():Promise<string>;

export function LaunchTeam(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string):Promise<brainbox.SessionActionResponse>;

export function ListAgentEvents(arg1:string,arg2:string,arg3:number):Promise<Array<brainbox.AgentEventEntry>>;

export function ListAgentRoles():Promise<Array<brainbox.AgentDefinition>>;

export function ListAgentState(arg1:main.AgentStateFilter):Promise<Array<brainbox.AgentStateItem>>;

export function ListAgents():Promise<Array<main.DetectedAgent>>;

export function ListAllRuleExecutions(arg1:string,arg2:number,arg3:number):Promise<Array<brainbox.RuleExecution>>;

export function ListArtifactsBuckets(arg1:string):Promise<Array<brainbox.ArtifactBucket>>;

export function ListArtifactsFolder(arg1:string,arg2:string):Promise<brainbox.ArtifactListing>;

export function ListAttention(arg1:string):Promise<Array<main.AttentionItem>>;

export function ListAutomationRules(arg1:string):Promise<Array<main.AutomationRule>>;

export function ListBackups():Promise<Array<string>>;

export function ListBundleSources(arg1:string):Promise<Array<main.BundleSourceView>>;

export function ListChannels(arg1:string):Promise<Array<brainbox.Channel>>;

export function ListCollectJobs(arg1:string):Promise<Array<main.CollectJob>>;

export function ListCollectedEntries(arg1:string,arg2:string,arg3:string):Promise<Array<main.CollectedEntry>>;

export function ListGatewayServers():Promise<Array<brainbox.GatewayServer>>;

export function ListHubTasks(arg1:string,arg2:string):Promise<Array<main.HubTask>>;

export function ListLiveLoops(arg1:string):Promise<Array<brainbox.LiveLoopSummary>>;

export function ListLoopTemplates():Promise<Array<string>>;

export function ListOllamaModels():Promise<Array<brainbox.OllamaModel>>;

export function ListPlaybooks(arg1:string):Promise<Array<brainbox.Playbook>>;

export function ListProfileDirs(arg1:string):Promise<Array<string>>;

export function ListProfileImages():Promise<Array<main.ProfileImageRow>>;

export function ListProfileTokens():Promise<Array<brainbox.ProfileTokenInfo>>;

export function ListRuleExecutions(arg1:string,arg2:string,arg3:number,arg4:number):Promise<Array<brainbox.RuleExecution>>;

export function ListRules(arg1:string):Promise<Array<brainbox.Rule>>;

export function ListRunners():Promise<Array<brainbox.Runner>>;

export function ListSchedules(arg1:string):Promise<Array<main.ScheduleRow>>;

export function ListSequenceRuns(arg1:string,arg2:number):Promise<Array<main.SequenceRunRow>>;

export function ListSequences():Promise<Array<main.Sequence>>;

export function ListServices():Promise<Array<main.ServiceStatus>>;

export function ListTasks(arg1:string,arg2:string,arg3:number):Promise<Array<main.TaskRow>>;

export function ListUpcomingFires(arg1:number):Promise<Array<main.UpcomingFire>>;

export function MinioIntegrationEnabled():Promise<boolean>;

export function MintGatewayToken(arg1:string,arg2:Array<string>,arg3:number,arg4:string):Promise<brainbox.GatewayToken>;

export function MintProfileToken(arg1:string,arg2:Array<string>,arg3:string):Promise<brainbox.ProfileToken>;

export function OpenLocalSession(arg1:string):Promise<void>;

export function OutboxPending():Promise<number>;

export function PostChannelMessage(arg1:string,arg2:brainbox.PostChannelMessageRequest):Promise<brainbox.ChannelMessage>;

export function PresignArtifactURL(arg1:string,arg2:string,arg3:string,arg4:number):Promise<brainbox.ArtifactPresignedURL>;

export function PreviewDispatch(arg1:brainbox.DispatchPreviewRequest):Promise<brainbox.DispatchPreview>;

export function PreviewPlan(arg1:string,arg2:string,arg3:Array<string>,arg4:Array<string>):Promise<brainbox.StepPlanResult>;

export function ProfileTokenCapabilities():Promise<Array<string>>;

export function ProfileTokenProfiles():Promise<Array<string>>;

export function PullOllamaModel(arg1:string):Promise<string>;

export function PurgeBackup(arg1:string):Promise<void>;

export function PutLoopTemplate(arg1:string,arg2:string,arg3:boolean):Promise<brainbox.LoopTemplate>;

export function RebuildBaseImage(arg1:main.BaseImageBuildRequest):Promise<void>;

export function RemoveChannelParticipant(arg1:string,arg2:string):Promise<brainbox.Channel>;

export function RescanAgents():Promise<Array<main.DetectedAgent>>;

export function RestartBrainboxAPI():Promise<void>;

export function RestoreAttention(arg1:string):Promise<void>;

export function RestoreProfile(arg1:string):Promise<void>;

export function RetryRuleExecution(arg1:number):Promise<brainbox.RuleExecution>;

export function RetryTask(arg1:string):Promise<void>;

export function RevokeProfileToken(arg1:string):Promise<void>;

export function RunCollectJobNow(arg1:string):Promise<void>;

export function RunMetricScript(arg1:string,arg2:string):Promise<string>;

export function RunPlaybook(arg1:string,arg2:string,arg3:string):Promise<brainbox.Playbook>;

export function RunPreflightChecks():Promise<Array<main.PreflightCheck>>;

export function RunSequence(arg1:string,arg2:string,arg3:string):Promise<string>;

export function SaveAutomationRule(arg1:main.AutomationRule):Promise<void>;

export function SaveCollectJob(arg1:main.CollectJob):Promise<main.CollectJob>;

export function SaveCustomBundleSource(arg1:string,arg2:string,arg3:string):Promise<void>;

export function SaveDashboardLayout(arg1:string,arg2:string):Promise<void>;

export function SaveRule(arg1:brainbox.Rule):Promise<brainbox.Rule>;

export function SaveSchedule(arg1:main.ScheduleRow):Promise<main.ScheduleRow>;

export function SaveSequence(arg1:main.Sequence):Promise<main.Sequence>;

export function ScanDiskUsage():Promise<main.DiskOverview>;

export function ScanProfiles():Promise<Array<main.Profile>>;

export function SearchAgentEvents(arg1:brainbox.SearchAgentEventsOptions):Promise<brainbox.SearchAgentEventsResult>;

export function SearchArtifactsFiles(arg1:string,arg2:string,arg3:string):Promise<any>;

export function SetActiveProfile(arg1:string):Promise<void>;

export function SetAgentEnabled(arg1:string,arg2:boolean):Promise<void>;

export function SetBundleSourceEnabled(arg1:string,arg2:string,arg3:boolean):Promise<void>;

export function SetConfig(arg1:string,arg2:string,arg3:string):Promise<void>;

export function SetDefaultCeiling(arg1:string,arg2:string):Promise<void>;

export function SetGatewayEnv(arg1:string,arg2:Record<string, string>):Promise<void>;

export function SetGatewayServerEnabled(arg1:string,arg2:boolean):Promise<void>;

export function SetHiddenProfiles(arg1:Array<string>):Promise<void>;

export function SetOTLPHost(arg1:string):Promise<void>;

export function SetProfileColor(arg1:string,arg2:string):Promise<void>;

export function SetProfileServerOverride(arg1:string,arg2:string,arg3:boolean):Promise<void>;

export function SetRegistrySettings(arg1:string,arg2:string):Promise<void>;

export function SetRuleEnabled(arg1:string,arg2:boolean):Promise<brainbox.RuleEnabledState>;

export function SetServiceConfig(arg1:string,arg2:boolean,arg3:string,arg4:string,arg5:boolean):Promise<void>;

export function SetTheme(arg1:string):Promise<void>;

export function SetTrustRule(arg1:string,arg2:string,arg3:string):Promise<void>;

export function StartLiveLoop(arg1:string,arg2:Record<string, any>):Promise<brainbox.LiveLoop>;

export function StartRunnerPairing(arg1:string,arg2:number,arg3:string):Promise<brainbox.PairingTicket>;

export function StartService(arg1:string):Promise<void>;

export function StartSession(arg1:string):Promise<brainbox.SessionActionResponse>;

export function StopService(arg1:string):Promise<void>;

export function StopSession(arg1:string):Promise<brainbox.SessionActionResponse>;

export function SubmitTask(arg1:brainbox.SubmitTaskRequest):Promise<main.HubTask>;

export function SubmitTaskAndWait(arg1:brainbox.WaitForTaskRequest):Promise<brainbox.WaitForTaskResponse>;

export function SyncProfileBundleNow(arg1:string):Promise<brainbox.BundlePutResult>;

export function TailLogs(arg1:string,arg2:number):Promise<Array<opensearch.LogEntry>>;

export function TestGatewayTools(arg1:string):Promise<brainbox.GatewayToolsResult>;

export function TestRuleEvent(arg1:Record<string, any>,arg2:Record<string, any>):Promise<brainbox.RuleTestResult>;

export function TestRulePattern(arg1:Record<string, any>,arg2:number):Promise<brainbox.RuleTestResult>;

export function TriggerRule(arg1:string,arg2:string,arg3:string):Promise<void>;

export function UpdateAgent(arg1:string,arg2:brainbox.UpdateAgentRequest):Promise<brainbox.AgentDefinition>;

export function UpdatePlaybook(arg1:string,arg2:brainbox.UpdatePlaybookRequest):Promise<brainbox.Playbook>;

export function UsableAgents():Promise<Array<main.DetectedAgent>>;

export function ValidateLoopTemplate(arg1:string):Promise<brainbox.LoopTemplateValidation>;
